### PR TITLE
ci: run `cue eval` to check stacks

### PR DESCRIPTION
**Pull request by yuyicai**

### CODE REVIEW

**Review by hongchaodeng — APPROVED** [review]

**Comment by hongchaodeng** [comment]
Please describe what this issue does in title

**Comment by yuyicai** [comment]
> Please describe what this issue does in title

Done!

**Comment by yuyicai** [comment]
But there is a problem with CI.  
I need some help! cc @hongchaodeng @lyzhang1999 @vgjm

**Comment by vgjm** [comment]
> There is a problem with CI. I need some help! cc @hongchaodeng @lyzhang1999 @vgjm

Now latest version of `hln` use dagger 0.2.9 by default.

**Comment by lyzhang1999** [comment]
I'm checking

**Comment by lyzhang1999** [comment]
got error in CI: `either --from-file or the combination of --docker-username, --docker*** --docker-server is required`
this error message seems does not come from stack.
but when I run `hln up` or `hln up -s gin-next` locally, It works.
image
@yuyicai

**Comment by yuyicai** [comment]
> Got error in CI: `either --from-file or the combination of --docker-username, --docker*** --docker-server is required` This error message seems does not come from stack. But when I run `hln up` or `hln up -s gin-next` locally, It works. image
> 
> And I noticed that there is some error in `Stack cue vendor`: image
> 
> @yuyicai

`dagger project update` would be executed inside `hln up`
This error does not affect  `hln up`

**Comment by yuyicai** [comment]
> Got error in CI: `either --from-file or the combination of --docker-username, --docker*** --docker-server is required` This error message seems does not come from stack. But when I run `hln up` or `hln up -s gin-next` locally, It works. image
> 
> And I noticed that there is some error in `Stack cue vendor`: image
> 
> @yuyicai

About the CI error `error: either --from-file or the combination of --docker-username, --docker*** --docker-server is required`  

Maybe the docker-password env is not available

**Comment by yuyicai** [comment]
The action workflow cannot get env `GITHUB_TOKEN`

Wrong：
```
  env:
    GITHUB_TOKEN: 
```
Correct：
```
  env:
    GITHUB_TOKEN: ***
```

**Comment by yuyicai** [comment]
Secrets are not passed to workflows that are triggered by a pull request from a fork.

**Comment by yuyicai** [comment]
Done!!!
cc @hongchaodeng @lyzhang1999 @vgjm

**Pull request merged**
